export const ASYNC_DEMO_INCREASE = 'ASYNC_DEMO_INCREASE';
export const ASYNC_DEMO_DECREASE = 'ASYNC_DEMO_DECREASE';
export const ASYNC_DEMO_INCREASE_AFTER = 'ASYNC_DEMO_INCREASE_AFTER';
export const ASYNC_DEMO_DECREASE_AFTER = 'ASYNC_DEMO_DECREASE_AFTER';
